### PR TITLE
Make it possible to run the tracker on Linux again

### PR DESCRIPTION
**Pull request by Sodivad**
Fixes it so yo can run it directly on a fresh checkout and conditionally improt windows modules

### CODE REVIEW

**Comment by Rchardon** [comment]
Interesting, does tracker work fine on Linux now ? Like if you middle click on the tracker, does it crash ?

**Comment by Sodivad** [comment]
I can run it and it shows the items. Have to just palce it in the correct folder since repentance does not have windows support and is  in a proton wine prefix. 

>Interesting, does tracker work fine on Linux now ? Like if you middle click on the tracker, does it crash ? 
Indeed, I also guarded that now since you can enable transparent in the settings also only on windows

**Comment by Rchardon** [comment]
Can you edit the readme with some instructions to place the tracker in the right folder please ? :)

**Comment by Rchardon** [comment]
Thank you so much :)

**Pull request merged**
